name: Build

on:
  push:
    branches: [master]

jobs:
  build_test_deploy:
    name: Build and test and deploy
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.11.3" # Define the elixir version [required]
          otp-version: "22.3" # Define the OTP version [required]
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_KEY}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      - name: Install dependencies
        run: mix deps.get
      - name: Check format
        run: mix format --check-formatted
      - run: npm install
        working-directory: ./assets
      - name: Create database
        run: mix ecto.create
      - name: Execute migrations
        run: mix ecto.migrate
      - name: Run tests
        run: mix test
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.1'
      - name: Deploy to Digital Ocean
        run: mix edeliver update production
